kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-vol
  namespace: planespotter
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mysql-ebs
